# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4cf56e5b63b5db6b0ff51fe829e3a8f6fcdf913d42654b214e4103bdd5e553cf66f71fee3252f58c769d962a6de178fb8c079ca9f483b81d0b992316e985693

test:
  secret_key_base: 57e09cf767129c83cd16000a8eec5981624bfdef64e7209410c24ebff997c159b72f776bf9ba3e572b3cf07c02b900decf79fc4dba21e04e5e7e3a230b14e389

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
